### ISSUE TITLE
姐姐姐姐

### ISSUE THREAD

**Issue by aoaoemoji** [xiaoxindada/SGSI-build-action#2]
姐姐，唔，希望姐姐可以完善下colorOS的支持，unpackops貌似也不行了，当然不排除是我自己的问题，唔 我到时候可以半夜陪你肝游戏 姐姐先努力下下啦

**Comment by xiaoxindada** [comment]
唔 11的工具年久失修啦 天天咕咕咕 等哪天不想咕咕了再大维修一次叭 小问题有点多咱是知道的 就是想咕咕咕 (狗头保命

**Comment by aoaoemoji** [comment]
咕咕咕姐姐 妹妹可是非常喜欢你的呦 我也会一直支持你的 能拉我进群么 呜呜

**Comment by xiaoxindada** [comment]
好的哦 加咱的qq叭

**Comment by aoaoemoji** [comment]
谢谢姐姐 么么哒
